### ISSUE TITLE
Does this plugin consume Firebase credits? Versus going to console directly

### ISSUE THREAD

**Issue by baptisteArno** [jsayol/vscode-firebase-explorer#23]

**Comment by TafadzwaD** [comment]
I was also thinking about the same issue😅.. Were you able to find out if that is the case or not?

**Comment by baptisteArno** [comment]
Yes, you use firestore credits **even** when you navigate into the console.

**Comment by TafadzwaD** [comment]
Came as a shock to me. I didn’t know that we are charged for accessing data using the console itself... Thank you for the info. The devil is in the details, a good reason why we should extensively go through the documentation. (Just saw the info from the documentation after your heads up)

**Comment by baptisteArno** [comment]
But then we could argue that they offer a generous free plan.

I suggest you take a look at Supabase, it's way better in lots of ways and you'll never be vendor locked 👍

**Comment by TafadzwaD** [comment]
Let me look into Supabase. I have been using Appwrite and it's working well for me, you can check it out as well
