### ISSUE TITLE
FR: Alphabetize the project list

### ISSUE THREAD

**Issue by samtstern** [jsayol/vscode-firebase-explorer#3]
I have like a million Firebase projects so I see this:
![image](https://user-images.githubusercontent.com/8466666/50249480-06c28d00-0393-11e9-9363-d73a00df18cc.png)

The order seems to be a bit random, would be good if they were alphabetized!

**Comment by jsayol** [comment]
Good idea! I'll change that.

Something else I noticed in your screenshot, there should be icons next to the account email and the project names. Are all the icons missing for you elsewhere too? It should look like the screenshot in the README.

**Comment by samtstern** [comment]
Yeah I noticed the same.  None of the icons are there for me ... I am on Google's Linux distro though (a Debian fork) so I don't know if the system has good emoji fonts or whatever it might be using.

**Comment by jsayol** [comment]
All the icons are SVGs distributed with the extension itself, and I'm also on Linux. That's strange, I'll look into it. What version of VSCode are you running?

**Comment by samtstern** [comment]
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.17.0-3rodete2-amd64

**Comment by jsayol** [comment]
Hey @samtstern, I just published a new version. The projects should now show in alphabetic order (ignoring case).

I also added proper XML headers to many of the SVG files that were missing them, let's see if that fixes it. I'm running the exact same version of VSCode as you so... strange. If this doesn't fix it let me know and I'll keep investigating.

**Comment by samtstern** [comment]
I've got alphabetized projects (:smile:) but no icons (:cry:).  Any logs I can pass on?

**Comment by jsayol** [comment]
Could you open the dev tools (`Help` -> `Toggle Developer Tools`) and see if there's any relevant error messages in the console?

**Comment by samtstern** [comment]
There are a lot of `Failed to load resource: net::ERR_FILE_NOT_FOUND` and the paths look like this:
```
/usr/local/google/home/samstern/Projects/firebase/myproject/assets/valuetype/boolean.svg
```

So looks like it's looking for the SVGs inside my project, rather than inside your plugin.

**Comment by jsayol** [comment]
That was super helpful! I was definitely not loading the icons correctly. I just published a new version, this one should fix it for sure :crossed_fingers:

**Comment by samtstern** [comment]
@jsayol woohooo!  Icons worked now.

**Comment by jsayol** [comment]
Awesome! Thanks for your help figuring this out :-)
