### ISSUE TITLE
Not able to add account to plugin

### ISSUE THREAD

**Issue by prgwar** [jsayol/vscode-firebase-explorer#5]
When I try to add account in the plugin I am getting error `command 'firebaseExplorer.accounts.add' not found`, Please help !!!

**Comment by jsayol** [comment]
Thanks for reporting this @prgwar! Sorry about this, I'm looking into it right now.

**Comment by jsayol** [comment]
I just published a new version fixing this issue (v0.2.8). It was caused by a regression introduced in the version published yesterday, in an overzealous attempt to reduce the final bundle size of the extension. Sorry about that!

Thanks again for reporting this :)
