### ISSUE TITLE
Question: What is the deal with that analytics file?

### ISSUE THREAD

**Issue by drKnoxy** [jsayol/vscode-firebase-explorer#6]
What info is being recorded?
Can I opt out?
Maybe add a note that you are collecting data, somewhere

**Comment by jsayol** [comment]
Yeah, that's a good point. I'm just collecting anonymous data to see how the extension is being used, but so far I haven't even looked at that analytics data at all so I think I'll just remove it from the extension altogether. 

Thanks for bringing this up, I should have addressed this sooner :)

**Comment by jsayol** [comment]
Done! I [removed all analytics collection](https://github.com/jsayol/vscode-firebase-explorer/commit/7906d6c9a086b03e453e68c0bb926cb8f5cc0926) and just published a new version (v0.2.9)

Thanks again for bringing this up!
